In [1]:
from pandas import read_csv
from scipy.stats import f_oneway

In [2]:
df = read_csv("tap_impact.csv")
df

    pid  base_err  round1_err  no_auto_err
0     2  2.183938    2.110033     3.246408
1     3  1.564262    1.217516     1.513434
2     4  2.788980    1.227798     1.313213
3     5  2.348893    1.811795     2.988355
4     6  4.174116    1.690578     1.935771
5     7  3.110060    1.969046     2.874716
6     8  2.738207    1.704590     2.337795
7     9  2.052657    1.347554     1.522405
8    10  2.478757    1.595592     3.526001
9    11  2.779050    1.443563     2.057362
10   12  1.682146    1.373115     1.444733
11   13  2.406263    1.533119     2.184888
12   14  2.475213    1.388989     1.623300
13   15  2.041809    1.516807     1.973411
14   16  1.710323    1.313109     1.730926
15   17  1.863016    1.363792     1.824824
16   18  3.486282    3.133281     2.873709
17   19  2.396504    2.430067     2.066365
18   20  1.984135    1.682781     1.747892
19   21  2.067320    1.429086     1.593438
20   22  2.197420    1.568133     1.696312
21   23  2.972060    1.631688     2.379322
22   24  2.915146    2.200224     3.644600
23   25  1.814064    1.543130     1.837297

In [3]:
baseline_err = df['base_err'].tolist()
round1_err = df['round1_err'].tolist()
zero_auto_err = df['no_auto_err'].tolist()

# did tapping negatively impact trajectory tracking? (compare baseline <-> zero_auto)
f_oneway(baseline_err, zero_auto_err)

######   TAPPING DIDN'T IMPACT THE PRIMARY TRAJECTORY TRACKING TASK!!!   ######

F_onewayResult(statistic=1.960857995902905, pvalue=0.16813080236506847)

In [6]:
baseline_ave = sum(baseline_err) / len(baseline_err)
print("Average error in baseline = %.3f" % baseline_ave)

Average error in baseline = 2.426